### ISSUE TITLE
Interpolate locations data to echograms

### ISSUE THREAD

**Issue by yalonzo** [OSOceanAcoustics/echopype#763] opened 2022-07-12 20:15 UTC
Hello guys,

Is possible to get the longitude and latitude data from Platform Group (see the screenshot) to the Sv data?
![image](https://user-images.githubusercontent.com/50753972/178585951-4123e836-8c4f-42b2-9ce8-c134d888026c.png)

I see that the latitude and longitude data are correlated to time1. However, the Sv data is correlated to time2
![image](https://user-images.githubusercontent.com/50753972/178583958-82cf21a9-b847-4299-b6e8-c08f17eeecdf.png)

The latitude data has a similar shape that time1
![image](https://user-images.githubusercontent.com/50753972/178585870-31f08f5f-9364-494c-b5d9-b27e3212b2cf.png)

And the Sv data has a similar shape that time2
![image](https://user-images.githubusercontent.com/50753972/178584392-b4375027-f7d2-4751-9e71-2f4d61240c05.png)

So, is possible to interpolate this time1 to time2? 🤔

This is because with that will be possible to scan where there are biomass or another species in the echogram according to locations

Thank you 😎

**Comment by emiliom** [comment] 2022-07-12 21:20
We've started working on that feature. See #749. @leewujung can comment on whether there's already useful functionality in that PR.

**Comment by leewujung** [comment] 2022-07-13 05:23
@yalonzo : the function in #749 is already in a functional form, but I want to move it to a different subpackage/module as part of our work in constructing the entire data processing pipeline, so it will remain a PR until probably sometime next week (and later be included in v0.6.2). Feel free to grab that function to use and comment on that PR for more discussion!

**Comment by leewujung** [comment] 2022-07-13 05:24
Duplicate of #725

**Comment by emiliom** [comment] 2022-08-04 15:54
I'm closing this issue, since we already identified it as a duplicate. See #725

**Closed by emiliom** 2022-08-04 15:54 UTC
Labels: duplicate, feature request
